name: terraform-action
on:
  push:
    branches:
    - master
    
env:
  TERRAFORM_VERSION: 1.0
  ENV: alpha

jobs:
  build-terraform-validate:
    runs-on: ubuntu-latest

    steps:
             
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
      
    - name: Checkout Vars repository
      uses: actions/checkout@v2

    - name: Checkout State repository
      uses: actions/checkout@v2
      with:
        repository: jefeish/terra-1-state
        path: terra-1-state
        
    - name: Checkout Plan repository
      uses: actions/checkout@v2
      with:
        repository: jefeish/terra-1-plan
        path: terra-1-plan

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
      
    - name: Terraform init
      run: cd terra-1-plan && terraform init
        
    - name: Terraform plan
      run: cd terra-1-plan && terraform plan -var-file=../environment/${{env.ENV}}/terraform.tfvars -state=../terra-1-state/environment/${{env.ENV}}/terraform.tfstate
    
    - name: Terraform apply
      run: cd terra-1-plan && terraform apply -auto-approve -var-file=../environment/${{env.ENV}}/terraform.tfvars -state=../terra-1-state/environment/${{env.ENV}}/terraform.tfstate
 
