name: terraform-action
on:
  push:
    branches:
    - master
    
env:
  TERRAFORM_VERSION: 1.0
  ENV: alpha
          
jobs:
  build-terraform-validate:
    runs-on: ubuntu-latest

    steps:
            
    - name: Checkout Vars repository
      uses: actions/checkout@v2

    - name: Checkout State repository
      uses: actions/checkout@v2
      with:
        repository: jefeish/terra-1-state
        path: terra-1-state
        
    - name: Checkout Plan repository
      uses: actions/checkout@v2
      with:
        repository: jefeish/terra-1-plan
        path: terra-1-plan

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        
    - name: where am I
      run: pwd && ls && ls -la ..
      
    - name: Terraform init
      run: cd terra-1-plan && terraform init
        
    - name: Terraform plan
      run: cd terra-1-plan && ls -la && terraform plan -var-file=../terra-1-vars/environment/${{env.ENV}}/terraform.tfvars -state=../terra-1-state/environment/${{env.ENV}}/terraform.tfstate
    
    - name: Terraform apply
      run: echo 'yes' | terraform apply -var-file=../terra-1-vars/environment/${{env.ENV}}/terraform.tfvars -state=../terra-1-state/environment/${{env.ENV}}/terraform.tfstate
